devsearch/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.projects, name="projects"),
    path('project/<str:pk>/', views.project, name="project"),       # name is used for redirecting ex: <a href="{% url 'project' %}">

    path('create-project/', views.createProject, name="create-project"),
    path('update-project/<str:pk>/', views.updateProject, name="update-project"),
    path('delete-project/<str:pk>/', views.deleteProject, name="delete-project"),   
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.profiles, name="profiles"),
]

projects/models.py
from django.db import models
import uuid
from users.models import Profile

# Create your models here.
class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)    #many to one relationship (profile => project)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default="default.jpg")
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank = True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    def __str__(self):
        return self.title

class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote')
    )
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=True)
    def __str__(self):
        return self.value

class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=True)
    def __str__(self):
        return self.name

users/models.py
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import User
import uuid
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null = True, blank = True)     # directly linking it to django's built in User model (if user is deleted, the profile model will also be deleted)
    name = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    username = models.CharField(max_length=100, blank=True, null=True)
    location = models.CharField(max_length=100, blank=True, null=True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(max_length=200, null=True, blank=True, upload_to='profiles/', default="profiles/user-default.png")
    social_github = models.CharField(max_length=200, null = True, blank = True)     # directly linking it to django's built in User model (if user is deleted, the profile model will also be deleted)
    social_twitter = models.CharField(max_length=200, null = True, blank = True)     # directly linking it to django's built in User model (if user is deleted, the profile model will also be deleted)
    social_linkedin = models.CharField(max_length=200, null = True, blank = True)     # directly linking it to django's built in User model (if user is deleted, the profile model will also be deleted)
    social_youtube = models.CharField(max_length=200, null = True, blank = True)     # directly linking it to django's built in User model (if user is deleted, the profile model will also be deleted)
    social_website = models.CharField(max_length=200, null = True, blank = True)     # directly linking it to django's built in User model (if user is deleted, the profile model will also be deleted)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=True)
    def __str__(self):
        return str(self.user.username)

class Skilll(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)    # CASCADE: if owner is deleted, skill is also deleted
    name = models.CharField(max_length=200, blank=True, null=True)
    descrption = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=True)
    def __str__(self):
        return str(self.name)

projects/forms.py
from django.forms import ModelForm
from django import forms
from .models import Project

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description', 'demo_link', 'source_link', 'tags']
        widgets = {
            'tags': forms.CheckboxSelectMultiple()
        }
    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():     #loop through all the fields in the form
            field.widget.attrs.update({'class': 'input'})

        # self.fields['title'].widget.attrs.update({'class': 'input', 'placeholder': 'Add Title'})      # add a class of input to the css

projects/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Project
from .forms import ProjectForm

# Create your views here.
def projects(request):
    projects = Project.objects.all()
    context = {'projects':projects}
    return render(request, 'projects/projects.html', context)

def project(request, pk):
    projectObj = Project.objects.get(id=pk)
    return render(request, 'projects/single-project.html', {'project':projectObj})

def createProject(request):
    form = ProjectForm()
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('projects')

    context = {'form':form}
    return render(request, "projects/project_form.html", context)


def updateProject(request, pk):
    project = Project.objects.get(id=pk)
    form = ProjectForm(instance =project)
    if request.method == "POST":
        form = ProjectForm(request.POST, instance = project)
        if form.is_valid():
            form.save()
            return redirect('projects')

    context = {'form':form}
    return render(request, "projects/project_form.html", context)

def deleteProject(request, pk):
    project = Project.objects.get(id=pk)
    context = {'object': project}
    if request.method == "POST":
        project.delete()
        return redirect('projects')
    return render (request, "projects/delete_template.html", context)

users/views.py
from django.shortcuts import render
from .models import Profile

# Create your views here.
def profiles(request):
    profiles = Profile.objects.all()
    context = {'profiles': profiles}
    return render(request, 'users/profiles.html', context)

projects/templates/projects/delete_template.html
{% extends 'main.html' %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{object}}"?</p>
    <a href="{% url 'projects' %}">
        Go Back 
    </a>
    <input type="submit" value="Confirm"/>
</form>

{% endblock content %}

projects/templates/projects/project_form.html
{% extends 'main.html' %}

{% block content %}

<!-- <h1>Project Form</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form> -->

    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="#"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" method="POST">
                    {% csrf_token %}

                    <!-- Input:Text -->
                    {% for field in form %}
                        <div class="form__field">
                            <label for="formInput#text"> {{field.label}} </label>
                            <!-- made field an input  in forms.py -->
                            {{field}}
                        </div>
                    {% endfor %}
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>


{% endblock %}

projects/templates/projects/projects.html
{% extends 'main.html' %}

{% block content %}

  <!-- Main Section -->
  <main class="projects">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>Search for <span>Projects</span></h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search By Projects </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by Project Title" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="projectsList">
      <div class="container">
        <div class="grid grid--three">
          
          {% for project in projects %}
          <div class="column">
            <div class="card project">
              <a href="{% url 'project' project.id %}" class="project">
                <img class="project__thumbnail" src="{{ project.featured_image.url }}" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">{{project.title}}</h3>
                  <p><a class="project__author" href="{% url 'project' project.id %}">By {{project.owner.name}}</a></p>
                  <p class="">Created on:  {{project.created}}</p>
                  <p class="project--rating">
                    <span style="font-weight: bold;">{{project.vote_ratio}} %</span> Positive
                    Feedback ({{project.vote_total}} Vote{{project.vote_total|pluralize:"s"}})
                  </p>
                  <div class="project__tags">
                    {% for tag in project.tags.all %}
                      <span class="tag tag--pill tag--main">
                        <small>{{tag}}</small>
                      </span>
                    {% endfor %}
                  </div>
                </div>
              </a>
            </div>
          </div>
          {% endfor %}

        </div>
      </div>
    </section>

  </main>

{% endblock content %}

projects/templates/projects/single-project.html
{% extends 'main.html' %}

{% block content %}

  <!-- Main Section -->
  <main class="singleProject my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <h3 class="singleProject__subtitle">Tools & Stacks</h3>
          <div class="singleProject__toolStack">
            {% for tag in project.tags.all %}
            <span class="tag tag--pill tag--sub tag--lg">
              <small>{{tag}}</small>
            </span>
            {% endfor %}
          </div>
          {% if project.source_link %}
            <a class="singleProject__liveLink" href="{{project.source_link}}" target="_blank"><i class="im im-external-link"></i>Source Code
            </a>
          {% endif %}
          {% if project.demo_link %}
            <a class="singleProject__liveLink" href="{{project.demo_link}}" target="_blank"><i class="im im-external-link"></i>Live Demo
            </a>
        {% endif %}
        </div>
        <div class="column column--2of3">
          <img class="singleProject__preview" src="{{ project.featured_image.url }}" alt="portfolio thumbnail" />
          <a href="profile.html" class="singleProject__developer">Md. Shahriar Parvez</a>
          <h2 class="singleProject__title">{{project.title}}</h2>
          <h3 class="singleProject__subtitle">About the Project</h3>
          <div class="singleProject__info">
            {{ project.description }}
            <br />
            <br />
          </div>

          <div class="comments">
            <h3 class="singleProject__subtitle">Feedback</h3>
            <h5 class="project--rating">
                {{project.vote_ratio}} % Postitive Feedback ({{project.vote_total}} Vote{{project.vote_total|pluralize:"s"}})
            </h5>

            <form class="form" action="#" method="POST">
              <!-- Textarea -->
              <div class="form__field">
                <label for="formInput#textarea">Comments: </label>
                <textarea class="input input--textarea" name="message" id="formInput#textarea"
                  placeholder="Write your comments here..."></textarea>
              </div>
              <input class="btn btn--sub btn--lg" type="submit" value="Comments" />
            </form>
            <div class="commentList">
              <div class="comment">
                <a href="profile.html">
                  <img class="avatar avatar--md"
                    src="https://pbs.twimg.com/profile_images/1335382240931368961/b3wSZKj4_400x400.jpg" alt="user" />
                </a>
                <div class="comment__details">
                  <a href="profile.html" class="comment__author">Sulamita Ivanov</a>
                  <p class="comment__info">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit alias numquam perferendis
                    mollitia minus minima exercitationem possimus ab deserunt qui, soluta iusto doloribus eveniet
                    similique consequuntur ratione, dignissimos ut magni laborum quo.
                  </p>
                </div>
              </div>
              <div class="comment">
                <a href="profile.html">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/33843378" alt="user" />
                </a>
                <div class="comment__details">
                  <a href="profile.html" class="comment__author">Dennis Ivanov</a>
                  <p class="comment__info">
                    Consectetur adipisicing elit. Reprehenderit alias numquam perferendis mollitia minus minima
                    exercitationem possimus ab deserunt qui, ratione, dignissimos ut magni laborum quo.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </main>


<!-- <img src="{{ project.featured_image.url }}" alt="">

<h2>{{project.title}}</h2>
<hr>
{% for tag in project.tags.all %}
    <span style="border:1px solid grey">{{tag}}</span>
{% endfor %}
<hr>
<p>{{project.description}}</p> -->
{% endblock content %}

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
  <!-- Icon - IconMonster -->
  <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
  <!-- Mumble UI -->
  <link rel="stylesheet" href="uikit/styles/uikit.css" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="styles/app.css" />

  <title>DevSearch - Connect with Developers!</title>
</head>

<body>
  <!-- Header Section -->
  <header class="header">
    <div class="container container--narrow">
      <a href="/" class="header__logo">
        <img src="images/logo.svg" alt="DevSearch Logo" />
      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          <li class="header__menuItem"><a href="index.html">Developers</a></li>
          <li class="header__menuItem"><a href="projects.html">Projects</a></li>
          <li class="header__menuItem"><a href="inbox.html">Inbox</a></li>
          <li class="header__menuItem"><a href="account.html">My Account</a></li>
          <li class="header__menuItem"><a href="login.html" class="btn btn--sub">Login/Sign Up</a></li>
        </ul>
      </nav>
    </div>
  </header>

  <!-- Main Section -->
  <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">
          <div class="column card">
            <div class="dev">
              <a href="/profile.html" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/22437186" alt="image" />
                  <div class="dev__meta">
                    <h3>Shahriar P. Shuvo</h3>
                    <h5>FullStack Web Designer & Developer</h5>
                  </div>
                </div>
                <p class="dev__info">
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate, ducimus inventore! Sunt,
                  veniam veritatis? Veritatis placeat, deleniti iure tempore veniam perspiciatis, soluta cupiditate
                  animi, exercitationem molestias nam doloremque architecto odit.
                </p>
                <div class="dev__skills">
                  <span class="tag tag--pill tag--main">
                    <small>JavaScript</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>React</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>SCSS</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>Nodejs</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>Express</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>GraphQL</small>
                  </span>
                </div>
              </a>
            </div>
          </div>
          <div class="column card">
            <div class="dev">
              <a href="/profile.html" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/1868782" alt="image" />
                  <div class="dev__meta">
                    <h3>Cody Seibert</h3>
                    <h5>React Developer, Coding Youtuber</h5>
                  </div>
                </div>
                <p class="dev__info">
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate, ducimus inventore! Sunt,
                  veniam veritatis? Veritatis placeat, deleniti iure tempore veniam perspiciatis, soluta cupiditate
                  animi, exercitationem molestias nam doloremque architecto odit.
                </p>
                <div class="dev__skills">
                  <span class="tag tag--pill tag--main">
                    <small>Elixir</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>F#</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>.NET</small>
                  </span>
                </div>
              </a>
            </div>
          </div>
          <div class="column card">
            <div class="dev">
              <a href="/profile.html" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/33843378" alt="image" />
                  <div class="dev__meta">
                    <h3>Dennis Ivy</h3>
                    <h5>Python & Django Developer</h5>
                  </div>
                </div>
                <p class="dev__info">
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate, ducimus inventore! Sunt,
                  veniam veritatis? Veritatis placeat, deleniti iure tempore veniam perspiciatis, soluta cupiditate
                  animi, exercitationem molestias nam doloremque architecto odit.
                </p>
                <div class="dev__skills">
                  <span class="tag tag--pill tag--main">
                    <small>Python</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>Django</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>Rest API</small>
                  </span>
                </div>
              </a>
            </div>
          </div>
          <div class="column card">
            <div class="dev">
              <a href="/profile.html" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/22437186" alt="image" />
                  <div class="dev__meta">
                    <h3>Shahriar P. Shuvo</h3>
                    <h5>FullStack Web Designer & Developer</h5>
                  </div>
                </div>
                <p class="dev__info">
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate, ducimus inventore! Sunt,
                  veniam veritatis? Veritatis placeat, deleniti iure tempore veniam perspiciatis, soluta cupiditate
                  animi, exercitationem molestias nam doloremque architecto odit.
                </p>
                <div class="dev__skills">
                  <span class="tag tag--pill tag--main">
                    <small>JavaScript</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>React</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>SCSS</small>
                  </span>
                </div>
              </a>
            </div>
          </div>
          <div class="column card">
            <div class="dev">
              <a href="/profile.html" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/22437186" alt="image" />
                  <div class="dev__meta">
                    <h3>Shahriar P. Shuvo</h3>
                    <h5>FullStack Web Designer & Developer</h5>
                  </div>
                </div>
                <p class="dev__info">
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate, ducimus inventore! Sunt,
                  veniam veritatis? Veritatis placeat, deleniti iure tempore veniam perspiciatis, soluta cupiditate
                  animi, exercitationem molestias nam doloremque architecto odit.
                </p>
                <div class="dev__skills">
                  <span class="tag tag--pill tag--main">
                    <small>JavaScript</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>React</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>SCSS</small>
                  </span>
                </div>
              </a>
            </div>
          </div>
          <div class="column card">
            <div class="dev">
              <a href="/profile.html" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/22437186" alt="image" />
                  <div class="dev__meta">
                    <h3>Shahriar P. Shuvo</h3>
                    <h5>FullStack Web Designer & Developer</h5>
                  </div>
                </div>
                <p class="dev__info">
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate, ducimus inventore! Sunt,
                  veniam veritatis? Veritatis placeat, deleniti iure tempore veniam perspiciatis, soluta cupiditate
                  animi, exercitationem molestias nam doloremque architecto odit.
                </p>
                <div class="dev__skills">
                  <span class="tag tag--pill tag--main">
                    <small>JavaScript</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>React</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>SCSS</small>
                  </span>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>

    <div class="pagination">
      <ul class="container">
        <li><a href="#" class="btn btn--disabled">&#10094; Prev</a></li>
        <li><a href="#" class="btn btn--sub">01</a></li>
        <li><a href="#" class="btn">02</a></li>
        <li><a href="#" class="btn">03</a></li>
        <li><a href="#" class="btn">04</a></li>
        <li><a href="#" class="btn">05</a></li>
        <li><a href="#" class="btn">06</a></li>
        <li><a href="#" class="btn">07</a></li>
        <li><a href="#" class="btn">08</a></li>
        <li><a href="#" class="btn">09</a></li>
        <li><a href="#" class="btn">10</a></li>
        <li><a href="#" class="btn">Next &#10095;</a></li>
      </ul>
    </div>
  </main>
</body>

</html>

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  
    <!-- Favicon -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
    <!-- Icon - IconMonster -->
    <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
    <!-- Mumble UI -->
    <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
    <!-- Dev Search UI -->
    <link rel="stylesheet" href="{% static 'styles/app.css' %}" />
  
    <title>DevSearch - Connect with Developers!</title>
</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}

    {% endblock content %}
    <p>FOOTER</p>
</body>
</html>

templates/navbar.html
{% load static %}

<header class="header">
    <div class="container container--narrow">
      <a href="{% url 'profiles' %}" class="header__logo">
        <img src="{% static 'images/logo.svg' %}" alt="DevSearch Logo" />
      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          <li class="header__menuItem"><a href="{% url 'profiles' %}">Developers</a></li>
          <li class="header__menuItem"><a href="{% url 'projects' %}">Projects</a></li>
          <li class="header__menuItem"><a href="">Inbox</a></li>
          <li class="header__menuItem"><a href="{% url 'create-project' %}">Add Project</a></li>
          <li class="header__menuItem"><a href="" class="btn btn--sub">Login/Sign Up</a></li>
        </ul>
      </nav>
    </div>
  </header>

users/templates/users/profiles.html
{% extends 'main.html' %}

{% block content %}
<main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">
            {% for profile in profiles %}
                <div class="column card">
                    <div class="dev">
                    <a href="" class="card__body">
                        <div class="dev__profile">
                        <img class="avatar avatar--md" src="{{profile.profile_image.url}}" alt="image" />
                        <div class="dev__meta">
                            <h3>{{profile.name}}</h3>
                            <h5>{{profile.short_intro|slice:"60"}}</h5>
                        </div>
                        </div>
                        <p class="dev__info">{{profile.bio|slice:"150"}}</p>
                        <h1>{{profile.skilll_set.all}}</h1>
                        <div class="dev__skills">
                          {% for skill in profile.skill_set.all %}
                            <span class="tag tag--pill tag--main">
                                <small>{{skill}}</small>
                            </span>
                          {%endfor%}
                        </div>
                    </a>
                    </div>
                </div>
            {% endfor %}

        </div>
      </div>
    </section>
  </main>
{% endblock content %}